services:
  postgres:
    image: postgres
    container_name: postgres
    networks:
      - fullstack-network
    ports:
      - 5433:5432
    env_file:
      - undefined-riddle-back/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    networks:
      - fullstack-network
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - .env

networks:
  fullstack-network:
    name: fullstack-network
    driver: bridge

volumes:
  postgres-volume: